name: Flask CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Static Code Check
      run: |
        pip install pylint
        pylint app.py || true

    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest

    - name: Build Docker Image
      run: |
        docker build -t flask-ci-app .
